/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookId = IDL.Nat;
export const ChapterId = IDL.Nat;
export const Book = IDL.Record({
  'title' : IDL.Text,
  'published' : IDL.Bool,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'genre' : IDL.Text,
  'chapterOrder' : IDL.Vec(ChapterId),
});
export const Chapter = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'order' : IDL.Nat,
  'bookId' : BookId,
});

export const idlService = IDL.Service({
  'createBook' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [BookId],
      [],
    ),
  'createChapter' : IDL.Func([BookId, IDL.Text, IDL.Text], [ChapterId], []),
  'deleteBook' : IDL.Func([BookId], [], []),
  'deleteChapter' : IDL.Func([ChapterId], [], []),
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getBook' : IDL.Func([BookId], [Book], ['query']),
  'getChapter' : IDL.Func([ChapterId], [Chapter], ['query']),
  'getChaptersByBook' : IDL.Func([BookId], [IDL.Vec(Chapter)], ['query']),
  'publishBook' : IDL.Func([BookId], [], []),
  'reorderChapters' : IDL.Func([BookId, IDL.Vec(ChapterId)], [], []),
  'updateBook' : IDL.Func(
      [BookId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateChapter' : IDL.Func([ChapterId, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookId = IDL.Nat;
  const ChapterId = IDL.Nat;
  const Book = IDL.Record({
    'title' : IDL.Text,
    'published' : IDL.Bool,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'genre' : IDL.Text,
    'chapterOrder' : IDL.Vec(ChapterId),
  });
  const Chapter = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'order' : IDL.Nat,
    'bookId' : BookId,
  });
  
  return IDL.Service({
    'createBook' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [BookId],
        [],
      ),
    'createChapter' : IDL.Func([BookId, IDL.Text, IDL.Text], [ChapterId], []),
    'deleteBook' : IDL.Func([BookId], [], []),
    'deleteChapter' : IDL.Func([ChapterId], [], []),
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getBook' : IDL.Func([BookId], [Book], ['query']),
    'getChapter' : IDL.Func([ChapterId], [Chapter], ['query']),
    'getChaptersByBook' : IDL.Func([BookId], [IDL.Vec(Chapter)], ['query']),
    'publishBook' : IDL.Func([BookId], [], []),
    'reorderChapters' : IDL.Func([BookId, IDL.Vec(ChapterId)], [], []),
    'updateBook' : IDL.Func(
        [BookId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateChapter' : IDL.Func([ChapterId, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };